#!/usr/bin/env bash

if [[ $# -eq 1 ]]; then
    selected=$1
else
    selected=$(find ~/Projects -mindepth 1 -maxdepth 1 -type d | fzf)
fi

if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-session -s $selected_name -c $selected
    exit 0
fi

if [[ -n $TMUX ]]; then
    current_session=$(tmux display-message -p '#S')
    session_count=$(tmux list-sessions | wc -l)

    if [[ $session_count -eq 1 ]] && [[ $current_session == "0" ]]; then
        tmux rename-session $selected_name
        tmux send-keys -t $selected_name "cd $selected" Enter
        tmux send-keys -t $selected_name "clear" Enter
        exit 0
    fi
fi

if ! tmux has-session -t=$selected_name 2> /dev/null; then
    tmux new-session -ds $selected_name -c $selected
fi

tmux switch-client -t $selected_name
